### PR TITLE
use browserify 11

### PR DESCRIPTION
**Pull request by feross**
Browserify 11 introduces a brand new `http` package that fixed lots of issues. The tests for my package `simple-peer` fail with the old `http` package because of it's bugs.

Can we use the latest browserify?

### CODE REVIEW

**Comment by feross** [comment]
cc @jhiesey

**Comment by defunctzombie** [comment]
No objections from me.

@feross isn't it a bit better to explicitly require the modules you need (even http) that way you don't rely on the version of browserify used?

@feross please update commit message to `package.json: update browserify to 11.1.0` thanks!

cc @vvo

**Comment by feross** [comment]
Commit message updated.

> isn't it a bit better to explicitly require the modules you need (even http) that way you don't rely on the version of browserify used?

@defunctzombie You're right that that would work. But sometimes you don't control the module or you want the same module to work in node and the browser. Also, then you won't inherit browserify bugfixes and improvements for free.

**Comment by defunctzombie** [comment]
Or inherit the bugs for free ;)

**Comment by vvo** [comment]
VErrrry late to the party, WFM :)

**Pull request merged**
