### PR TITLE
update convert-source-map and check for large sources

### PR DESCRIPTION
**Pull request by phated**
ref https://github.com/thlorenz/convert-source-map/pull/18

I'm not sure of a good size for `isLarge` length so I chose 1000 arbitrarily.

### CODE REVIEW

**Comment by defunctzombie** [comment]
Seems like isLarge is no longer needed per that linked issue?

**Comment by phated** [comment]
The API now needs a flag specifying whether a source is large or not. Link: https://github.com/thlorenz/convert-source-map#fromsourcesource-largesource
If `largeSource` is true, it uses indexOf instead of the regexp.

**Comment by defunctzombie** [comment]
Are you running into this large source issue using zuul? Or is this pre-emptive to what might occur?

**Comment by phated** [comment]
I'm actually running into this on a project I am running into.  I think the `isLarge` length can probably be adjusted higher but I don't have a good way to test different sizes.

**Comment by defunctzombie** [comment]
Is the `isLarge` value basically, "When do I use the new algo versus the old?" If it is, I would use your current failing situation as a gage and pick a value that basically starts making it work for you and then maybe pick something slightly lower. That is how I would go about determining that since there does seem to be a possible "downside" to using the new algo. But if that is the only solution for large files, then we can mitigate possible breakage by focusing on only using it when absolutely needed.

**Comment by phated** [comment]
Good call.  I actually just tested with convert-source-map@1.0.0 and the simplified regexp they introduced sometime since 0.4.1 has actually fixed the problem with my 37,762 line file. Should I just remove the `isLarge` check or set it at something like 40k?

**Comment by defunctzombie** [comment]
I would remove unless you can find. Case when it is needed.

**Comment by phated** [comment]
Alright, I've updated the PR to just update the convert-source-map dependency to 1.0

**Pull request merged**
