### PR TITLE
Disambiguate with other projects named zuul

### PR DESCRIPTION
**Pull request by SpamapS**
There are two other projects named Zuul. Remove the confusion.

### CODE REVIEW

**Comment by SpamapS** [comment]
Hi! It would be helpful to me to understand why you closed this without a comment. Is there something wrong with it?

**Comment by defunctzombie** [comment]
Between google and the project README I think someone is capable of disambiguating the projects and locating the project they need.

**Comment by SpamapS** [comment]
Wouldn't you rather you actually tell them when they've made a mistake, rather than people being confused? Not everybody will understand what "zuul" is and both of our tools are testing tools.

Anyway, I think it would be nice if you could return the favor. We were nice enough to actually tell people about your project in case they accidentally arrive in our docs:

https://zuul-ci.org/docs/zuul/

**Comment by defunctzombie** [comment]
Since you have added it to zuul-ci I will reciprocate.

**Pull request merged**
