### PR TITLE
add electron support using --electron flag

### PR DESCRIPTION
**Pull request by JamesKyburz**
Make it possible to run tests in an atom-shell environment.

### CODE REVIEW

**Comment by vvo** [comment]
I don't even know what's atom-shell. Can you show us how a zuul test runs in it and what's the workflow you have with it?

It seems to include a lot of atom-shell specifics inside zuul. Maybe we should start making zuul pluggable (plugin interface).

**Comment by defunctzombie** [comment]
+1 to what @vvo said. I have a vague idea of what Atom shell is but would love to get a more detailed explanation. Maybe something we can turn into a wiki page to guide other users. My initial gut reaction is that this is probably something cool :)

**Comment by JamesKyburz** [comment]
@vvo @defunctzombie Firstly atom-shell was renamed to [electron](https://github.com/atom/electron).

I have changed the pull request and commit message to reflect the name change.

Here goes to sell why I think it would be a good idea to add :)

Taken from the documentation "Electron is a javascript runtime that bundles Node.js and Chromium."

Electron is what atom the editor used to build upon.

The primary use case for Electron is to built native apps for Linux, OSX and Windows using js, css & html.
Because the entry point to electron is a js file and you control the window you can for example run with a hidden window ideal for headless-ish tests. To run an app you can invoke it using the `electron` command without having to build the app!

The environment is like the node console and chrome dev tools in one, so require('http').createServer and document.createElement in the same context! 

So why is this a good idea?

Well although the environment is not a browser, adding tools like screenshots and breakpoints that open dev tools automatically can improve the experience of running tests and debugging. Also writing tests for cutting edge features not available in phantom would be possible without running --local.

Another use case would be the ability for an electron app author to test the electron environment using zuul.

I wanted to added to zuul after I wrote [tape-run-electron](https://github.com/JamesKyburz/tape-run-electron) seeing how easy it was.

I use zuul for my open source projects, being able to switch between phantom and saucelabs + having a testserver like testling is great! I've had alot of fun running it with the --electron flag.

I put together a [demo-video](https://dl.dropboxusercontent.com/u/11380518/electron.mp4) to show off some stuff. I put it together quickly last night before I noticed atom-shell got renamed!

@vvo Re the plugin question. That would be nice, I copied the structure of phantom + two tiny files to inject the tests in the electron window. Nothing gets run without the --electron flag and there are no extra dependencies required. Installing electron-prebuilt needs to be done separately when using --electron.

Adding some plugin mechanism for zuul would be nice, and could be added later on.

What do you think?

**Comment by vvo** [comment]
Ok got it, so it's like electron testing + electron local testing easily done with zuul?

Fine with me has it does not interfere with other code and seems to provide something very useful for electron devs.

**Comment by JamesKyburz** [comment]
@vvo exactly. Thanks for your quick response!

**Comment by vvo** [comment]
@defunctzombie thoughts?

**Comment by JamesKyburz** [comment]
What do you think, could this be merged? Let me know if you want any changes!

**Comment by defunctzombie** [comment]
I think this is awesome! Thanks for the video, it really helped me understand how a dev benefits from this feature.

Could you explain what `lib/electron-inject.js` and `lib/electron-run.js` do? I see some require statements for modules not in package.json so I assume these are run in the actual electron shell environment.

I will indeed merge this.

**Comment by JamesKyburz** [comment]
@defunctzombie great!

You are right that all the requires in `electron-run.js` and `electron-inject.js` are in an electron context.

`lib/Electron.js` runs electron with `lib/electron-run.js` sent as an argument.

`electron-run.js` creates the browser window and runs `electron-inject.js`. It also sets up the ipc mechanism writing the zuul messages to `console.log` from `window.zuul_msg_bus`

`electron_inject.js` runs a loop extracting messages from `window.zuul_msg_bus.splice` sending them the main electron process (`electron-run`)

When the msg.type === 'done' the tests are finished and the electron process terminates.

**Comment by dotnetmentor** [comment]
Great thx!

**Comment by JamesKyburz** [comment]
Thanks!

**Pull request merged**
