### PR TITLE
saucebrowser: use appium 1.5.x

### PR DESCRIPTION
**Pull request by lpinca**
Appium [1.5.2](https://github.com/appium/appium/releases/tag/v1.5.2) is now available on Sauce Labs.

### CODE REVIEW

**Comment by defunctzombie** [comment]
What does this change for users?

**Comment by lpinca** [comment]
@defunctzombie AFAIK nothing.

**Comment by vvo** [comment]
I bet this should bring stability on the saucelabs end.

**Comment by lpinca** [comment]
Yeah and bug fixes according to the change log.

**Comment by lpinca** [comment]
There is an issue with this. An error is thrown when testing iOS 7.0 or 7.1:

```
iphone@7.0: [init({"name":"eventemitter3","tags":[],"browserName":"iphone","version":"7.0","platform":"Mac 10.9","appium-version":"1.5","record-screenshots":false,"record-video":false})] The environment you requested was unavailable.: Appium 1.5.2 does not support Mac 10.9. Please check our platform configurator (https://saucelabs.com/docs/platforms)
```

This is odd because older versions (6.x and 5.x) work fine.
Maybe it makes sense to revert this before a new release is cut.

**Pull request merged**
