### PR TITLE
fix: always return a uniq list of browser-version-platform

### PR DESCRIPTION
**Pull request by vvo**
cc @mcous and @defunctzombie :)

### CODE REVIEW

**Comment by vvo** [comment]
This was previously failing

**Comment by vvo** [comment]
test were OK on my comp, still the infamous hidden env variables here. maybe we should make them public, I have seen big projects like ember making the keys public for ease of contribution

**Comment by defunctzombie** [comment]
What was the issue here?

**Comment by vvo** [comment]
> What was the issue here?

Before this patch, when specifying:

```js
var browsers = [{
  name: 'ipad',
  version: ['7.1', '-2..8.4', '-2..latest']
}];
```

Ipad versions available on saucelabs: 8.4, 8.3, 8.2, 8.1, 8.0, 7.1, 7.0
Ipad versions selected (by the previous conf): 8.4, 8.3, 8.2, 8.4, 8.3, 8.2, 7.1

So versions were duplicated (same problem when specifying platforms).

Here I only enfore that you cannot have the same version on the same platform. Wonder if people were relying on this bug, pretty sure not.

**Comment by defunctzombie** [comment]
Sounds good. If anyone is relying on the bug they can let us know and we will make a note of behavior in the future. Seems like a worthwhile change to me.

**Pull request merged**
