### PR TITLE
Add "wait" field to .zuul.yml to wait for starting user_server

### PR DESCRIPTION
**Pull request by crumbjp**
Want to specify the wait time as bellow.

```yml
server:
  cmd: coffee bin/my_server.coffee
  cwd: ../my_server
  wait: 10000
```

### CODE REVIEW

**Comment by vvo** [comment]
Hey, hi, what's the use case you have?

**Comment by crumbjp** [comment]
We starts our server program as the zuul's user-server.
Work well at the first time.
But our program get grow and start slowly ...
So must wait for server startup before starting test.

**Comment by vvo** [comment]
There may be another option for your particular usecase: have a /ready route on your webserver and call it from your tests.

When it will respond then your server is ready, what do you think @crumbjp?

**Comment by vvo** [comment]
The setTimeout answer is never a consistent answer.

**Comment by defunctzombie** [comment]
While I agree with you @vvo, I think this is something we can do easily to "patch" the issue for users. The `/ready` route approach or something else is more work an end user would have to do that is just boilerplate.

Alternatively, we could have zuul itself understand when the web server has started and then load the test files. I think this wait is a simpler hack and would be ok merging it until there is a better solution.

**Comment by vvo** [comment]
Fine with me @defunctzombie.

> Alternatively, we could have zuul itself understand when the web server has started and then load the test files. I think this wait is a simpler hack and would be ok merging it until there is a better solution.

I cannot see how we would do that easily since we are only spawning the user server.

**Comment by defunctzombie** [comment]
Because we know what port the server will start up on we could tcp ping it
until a connection could be established.

**Pull request merged**
