### PR TITLE
Upgrade dependencies to avoid deprecations

### PR DESCRIPTION
**Pull request by josephfrazier**
This simply upgrades dependencies to avoid using:

1. `os.tmpDir()`
2. `options.customFds` in `child_process`

Note: The following tests failed for me locally (even before these changes),
      despite having ~/.zuulrc as well as `SAUCE_USERNAME` and `SAUCE_ACCESS_KEY`:

* `mocha-qunit - phantom`
* `mocha-qunit - sauce`
* `mocha-bdd - phantom`
* `tape - phantom`

After commenting them out, the remaining tests pass.

EDIT: After a little digging, I found the failure to be caused by this error:

```
You may not run more than 2 tunnels over a single ngrok session without an account.
You may increase this limit by signing up and upgrading.
The tunnels already running on this session are:

    - https://a8574938.ngrok.io
    - http://229b2f08.ngrok.io
    - http://a8574938.ngrok.io

Sign up at: https://ngrok.com/signup

If you have already signed up, make sure your authtoken is installed.
Your authtoken is available on your dashboard: https://dashboard.ngrok.com

ERR_NGROK_323
```

After signing up and following the `authtoken` instructions, I got a little further, until I hit this error:

```
Your account may not run more than 4 tunnels over a single ngrok client session.
The tunnels already running on this session are:

    - https://e3a7d2e7.ngrok.io
    - http://6f189147.ngrok.io
    - https://6f189147.ngrok.io
    - http://4e78fb86.ngrok.io
    - http://2332a103.ngrok.io
    - https://724ae5e0.ngrok.io
    - http://fbae9ae5.ngrok.io


ERR_NGROK_324
```

I don't really feel like paying for ngrok right now, so I tried to use localtunnel instead, by applying this patch:

<details>

```diff
diff --git a/test/integration/capabilities.js b/test/integration/capabilities.js
index 505caf6..d23247f 100644
--- a/test/integration/capabilities.js
+++ b/test/integration/capabilities.js
@@ -10,7 +10,6 @@ test('capabilities config', function(done) {
                 public: 'private'
             }
         },
-        tunnel: 'ngrok'
     };
 
     var zuul = Zuul(config);
diff --git a/test/integration/jamine-phantom.js b/test/integration/jamine-phantom.js
index c108b77..dfba19a 100644
--- a/test/integration/jamine-phantom.js
+++ b/test/integration/jamine-phantom.js
@@ -12,7 +12,6 @@ test('jasmine - phantom', function(done) {
         phantom: true,
         concurrency: 1,
         files: [__dirname + '/../fixtures/jasmine/test.js'],
-        tunnel: 'ngrok'
     };
 
     var zuul = Zuul(config);
diff --git a/test/integration/mocha-qunit-phantom.js b/test/integration/mocha-qunit-phantom.js
index 8ba2e30..043325b 100644
--- a/test/integration/mocha-qunit-phantom.js
+++ b/test/integration/mocha-qunit-phantom.js
@@ -12,7 +12,6 @@ test('mocha-qunit - phantom', function(done) {
         phantom: true,
         concurrency: 1,
         files: [__dirname + '/../fixtures/mocha-qunit/test.js'],
-        tunnel: 'ngrok'
     };
     var zuul = Zuul(config);
 
diff --git a/test/integration/mocha-qunit-sauce.js b/test/integration/mocha-qunit-sauce.js
index ef0092a..4c94576 100644
--- a/test/integration/mocha-qunit-sauce.js
+++ b/test/integration/mocha-qunit-sauce.js
@@ -14,7 +14,6 @@ test('mocha-qunit - sauce', function(done) {
         username: auth.username,
         concurrency: 5,
         key: auth.key,
-        tunnel: 'ngrok'
     };
 
     var zuul = Zuul(config);
diff --git a/test/integration/mochabdd-phantom.js b/test/integration/mochabdd-phantom.js
index 9435d02..31f8241 100644
--- a/test/integration/mochabdd-phantom.js
+++ b/test/integration/mochabdd-phantom.js
@@ -12,7 +12,6 @@ test('mocha-bdd - phantom', function(done) {
         phantom: true,
         concurrency: 1,
         files: [__dirname + '/../fixtures/mocha-bdd/test.js'],
-        tunnel: 'ngrok'
     };
 
     var zuul = Zuul(config);
diff --git a/test/integration/tape-phantom.js b/test/integration/tape-phantom.js
index 2e382b5..47b918a 100644
--- a/test/integration/tape-phantom.js
+++ b/test/integration/tape-phantom.js
@@ -13,7 +13,6 @@ test('tape - phantom', function(done) {
         phantom: true,
         concurrency: 1,
         files: [__dirname + '/../fixtures/tape/test.js'],
-        tunnel: 'ngrok'
     };
 
     var zuul = Zuul(config);
```
</details>

However, localtunnel seems to get caught in a loop of repeatedly printing:

```
  zuul:sauce:internet explorer:8 waiting for test results from https://wtyfrtgyzz.localtunnel.me/__zuul +2s
  zuul:sauce:internet explorer:8 res.length: 0 +288ms
  zuul:sauce:internet explorer:8 fetching more results +0ms
```

### CODE REVIEW

**Comment by phated** [comment]
:-1: on dropping 0.10 support currently.

**Comment by josephfrazier** [comment]
FWIW, I'm seeing the tests fail on 0.10 currently (this is without any of the patching I edited into the OP):

```
  1)  mocha-qunit - sauce:
     Error: done() invoked with non-Error: [object Object]
      at /Users/josephfrazier/workspace/zuul/node_modules/mocha/lib/runnable.js:206:38
      at proxy (/Users/josephfrazier/workspace/zuul/node_modules/after/index.js:19:13)
      at Zuul.<anonymous> (/Users/josephfrazier/workspace/zuul/test/integration/mocha-qunit-sauce.js:49:13)
      at Zuul.emit (events.js:95:17)
      at SauceBrowser.<anonymous> (/Users/josephfrazier/workspace/zuul/lib/zuul.js:146:22)
      at SauceBrowser.emit (events.js:95:17)
      at finish_shutdown (/Users/josephfrazier/workspace/zuul/lib/SauceBrowser.js:262:18)
      at Object.callback (/Users/josephfrazier/workspace/zuul/lib/SauceBrowser.js:287:13)
      at cb (/Users/josephfrazier/workspace/zuul/node_modules/wd/lib/webdriver.js:216:36)
      at null.<anonymous> (/Users/josephfrazier/workspace/zuul/node_modules/wd/lib/callbacks.js:42:9)
      at cb (/Users/josephfrazier/workspace/zuul/node_modules/wd/lib/webdriver.js:160:22)
      at /Users/josephfrazier/workspace/zuul/node_modules/wd/lib/webdriver.js:174:5
      at Request._callback (/Users/josephfrazier/workspace/zuul/node_modules/wd/lib/http-utils.js:85:7)
      at Request.self.callback (/Users/josephfrazier/workspace/zuul/node_modules/wd/node_modules/request/request.js:364:22)
      at Request.emit (events.js:98:17)
      at Request.<anonymous> (/Users/josephfrazier/workspace/zuul/node_modules/wd/node_modules/request/request.js:1318:14)
      at Request.emit (events.js:117:20)
      at IncomingMessage.<anonymous> (/Users/josephfrazier/workspace/zuul/node_modules/wd/node_modules/request/request.js:1266:12)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:944:16
      at process._tickCallback (node.js:458:13)



npm ERR! Test failed.  See above for more details.
```

They're also failing on Travis: https://travis-ci.org/defunctzombie/zuul/builds/215547314

**Comment by phated** [comment]
Tests failing !== removal of support

**Comment by josephfrazier** [comment]
Good point. Yeah... based on the [error message](https://travis-ci.org/defunctzombie/zuul/builds/229196408#L446-L449), this would indeed drop support for Node 0.10. I even tried running the tests with `node --harmony` (as suggested [here](https://stackoverflow.com/questions/22603078/syntaxerror-use-of-const-in-strict-mode))with `DEBUG=zuul* ./node_modules/.bin/mocha --harmony --ui qunit --timeout 0 --bail -- test/index.js`, but that just results in another error:

```
/Users/josephfrazier/workspace/zuul/node_modules/wd/node_modules/lodash/lodash.js:1243
    set.forEach(function(value) {
        ^
TypeError: Object #<Set> has no method 'forEach'
```

which cannot be worked around with further `node` flags, according to http://node.green/ :(

**Pull request closed without merging**
