### PR TITLE
Fix jasmine client to report error correctly.

### PR DESCRIPTION
**Pull request by andreypopp**

### CODE REVIEW

**Comment by vvo** [comment]
@andreypopp Do you think we can write a failing test or can you link to a ressource saying that "this is the right thing to do"?

**Comment by andreypopp** [comment]
Yes I can write a test case, not sure when I have time for that though.

**Comment by vvo** [comment]
Just explaining why it solves the issue or enhancing the current test is enough.

**Comment by defunctzombie** [comment]
@andreypopp did the jasmine api for results change?

**Comment by andreypopp** [comment]
I don't know about API change but now without this patch I get empty error message reported on top of stack trace.

**Pull request merged**
