### PR TITLE
remove .configureHttp call, specify appium version

### PR DESCRIPTION
**Pull request by vvo**

### CODE REVIEW

**Comment by vvo** [comment]
@rase- this seems pretty stable, running iphone tests without a failure right now, multiple times

**Comment by vvo** [comment]
for reference, those are the wd defaults: https://github.com/admc/wd/blob/f49065fa8ff91411f70972f149e90b7f97f4cd39/lib/config.js

**Comment by rase-** [comment]
@defunctzombie was the current retry delay chosen for a reason? Unsure about that, but otherwise LGTM.

**Comment by vvo** [comment]
https://github.com/defunctzombie/zuul/commit/df0ed8d04619d11427dd5b0c1771f7f66ad5c6b0

**Comment by rase-** [comment]
@vvo: I'd say let's just specify the appium version for now and let's revisit the config separately, if that sounds good to you.

**Comment by vvo** [comment]
You mean you want two different PRS? Or just the appium version PR? Working good on all my projects right now

**Comment by defunctzombie** [comment]
The current retry delay was not chosen for any particular reason.

**Comment by rase-** [comment]
Ok, I think we should be good with the defaults for now then. Thanks @vvo!

**Comment by parshap** [comment]
:+1:

**Pull request merged**
